### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: yaml_configs/ds_z3_config.json
pref_beta: 0.01
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: evol
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama_3_instruct/lora/dpo
logging_steps: 2
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 7.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 480000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

# wandb
report_to: wandb
run_name: llama3_instruct_full # optional