### model
model_name_or_path: Qwen/CodeQwen1.5-7B-Chat

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: yaml_configs/ds_z3_config.json
pref_beta: 0.01
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: code_qwen_v1.5_inf
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/code_llm/trained/code_qwen_v1.5/full/dpo/inf/
logging_steps: 2
save_steps: 2500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 480000000

### eval
val_size: 0.005
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 200

# wandb
report_to: wandb
run_name: code_qwen_v1.5_dpo_full_inf # optional