### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct

### method
stage: rm
do_train: true
finetuning_type: full
deepspeed: yaml_configs/ds_z3_config.json

### dataset
dataset: cross_models_1
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/code_llm/trained/qwen_coder_2.5/full/rm/cross_models_1/
logging_steps: 10
save_steps: 2500
plot_loss: true
overwrite_output_dir: true
stage: rm

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 480000000

### eval
val_size: 0.005
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 200

# wandb
report_to: wandb
run_name: qwen_coder_2.5_rm_full_cross_models_1 # optional